brownMandM: Remove this line before submitting.

response: >
  Hi there, it looks like you've not followed the template completely. Please re-read the template and ensure you've followed all the instructions. This helps us review exercises quicker!